# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend/UI/infection-spread.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.canvas = QtWidgets.QLabel(self.centralwidget)
        self.canvas.setGeometry(QtCore.QRect(270, 210, 47, 13))
        self.canvas.setText("")
        self.canvas.setObjectName("canvas")
        self.coordinateBox = QtWidgets.QCheckBox(self.centralwidget)
        self.coordinateBox.setGeometry(QtCore.QRect(250, 100, 111, 31))
        self.coordinateBox.setObjectName("coordinateBox")
        self.dummyButton = QtWidgets.QPushButton(self.centralwidget)
        self.dummyButton.setGeometry(QtCore.QRect(250, 140, 151, 23))
        self.dummyButton.setDefault(False)
        self.dummyButton.setObjectName("dummyButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.coordinateBox.setText(_translate("MainWindow", "Show coordinates"))
        self.dummyButton.setText(_translate("MainWindow", "Create dummy map"))
